all: 
	clear
	gcc -std=c11 -mfma -o matrix_lib_test matrix_lib_test.c matrix_lib.c timer.c
	./matrix_lib_test 5.0 2048 2048 2048 2048 8 floats_2048_2.0f.dat floats_2048_5.0f.dat result1.dat result2.dat